export const POSSIBLE_ANSWERS = [
        "10th squad sigil",
        "20th anniversary cape",
        "20th anniversary hat",
        "20th anniversary top",
        "24 carat sword",
        "3rd age amulet",
        "3rd age axe",
        "3rd age bow",
        "3rd age cloak",
        "3rd age druidic cloak",
        "3rd age druidic staff",
        "3rd age full helmet",
        "3rd age kiteshield",
        "3rd age longsword",
        "3rd age mage hat",
        "3rd age pickaxe",
        "3rd age platebody",
        "3rd age platelegs",
        "3rd age plateskirt",
        "3rd age range coif",
        "3rd age range legs",
        "3rd age range top",
        "3rd age robe",
        "3rd age robe top",
        "3rd age vambraces",
        "3rd age wand",
        "4th birthday hat",
        "A jester stick",
        "A powdered wig",
        "Abyssal bludgeon",
        "Abyssal bracelet",
        "Abyssal dagger",
        "Abyssal lantern",
        "Abyssal tentacle",
        "Abyssal tentacle (or)",
        "Abyssal whip",
        "Abyssal whip (or)",
        "Accumulator max cape",
        "Accumulator max hood",
        "Adamant 2h sword",
        "Adamant arrow",
        "Adamant axe",
        "Adamant battleaxe",
        "Adamant bolts",
        "Adamant boots",
        "Adamant brutal",
        "Adamant cane",
        "Adamant chainbody",
        "Adamant claws",
        "Adamant crossbow",
        "Adamant dagger",
        "Adamant dart",
        "Adamant defender",
        "Adamant dragon mask",
        "Adamant fire arrow",
        "Adamant full helm",
        "Adamant full helm (g)",
        "Adamant full helm (t)",
        "Adamant gloves",
        "Adamant halberd",
        "Adamant hasta",
        "Adamant javelin",
        "Adamant kiteshield",
        "Adamant knife",
        "Adamant longsword",
        "Adamant mace",
        "Adamant med helm",
        "Adamant pickaxe",
        "Adamant platebody",
        "Adamant platebody (g)",
        "Adamant platebody (t)",
        "Adamant platelegs",
        "Adamant platelegs (g)",
        "Adamant platelegs (t)",
        "Adamant plateskirt",
        "Adamant scimitar",
        "Adamant spear",
        "Adamant sq shield",
        "Adamant sword",
        "Adamant thrownaxe",
        "Adamant warhammer",
        "Agility cape",
        "Agility hood",
        "Ahrims hood",
        "Ahrims robeskirt",
        "Ahrims robetop",
        "Ahrims staff",
        "Air battlestaff",
        "Air tiara",
        "Ale of the gods",
        "Amethyst arrow",
        "Amethyst broad bolts",
        "Amethyst dart",
        "Amethyst fire arrow",
        "Amethyst javelin",
        "Amulet of accuracy",
        "Amulet of avarice",
        "Amulet of blood fury",
        "Amulet of bounty",
        "Amulet of chemistry",
        "Amulet of defence",
        "Amulet of defence (t)",
        "Amulet of fury",
        "Amulet of fury (or)",
        "Amulet of glory",
        "Amulet of glory (t)",
        "Amulet of magic",
        "Amulet of magic (t)",
        "Amulet of nature",
        "Amulet of power",
        "Amulet of power (t)",
        "Amulet of strength",
        "Amulet of the damned",
        "Amulet of the eye",
        "Amulet of torture",
        "Amys saw",
        "Ancestral hat",
        "Ancestral robe bottom",
        "Ancestral robe top",
        "Ancient blessing",
        "Ancient bracers",
        "Ancient chaps",
        "Ancient cloak",
        "Ancient coif",
        "Ancient crozier",
        "Ancient dhide body",
        "Ancient dhide boots",
        "Ancient dhide shield",
        "Ancient full helm",
        "Ancient godsword",
        "Ancient halo",
        "Ancient kiteshield",
        "Ancient mace",
        "Ancient mitre",
        "Ancient mjolnir",
        "Ancient platebody",
        "Ancient platelegs",
        "Ancient plateskirt",
        "Ancient robe legs",
        "Ancient robe top",
        "Ancient staff",
        "Ancient stole",
        "Ancient wyvern shield",
        "Anger battleaxe",
        "Anger mace",
        "Anger spear",
        "Anger sword",
        "Angler boots",
        "Angler hat",
        "Angler top",
        "Angler waders",
        "Ankou gloves",
        "Ankou mask",
        "Ankou socks",
        "Ankou top",
        "Ankous leggings",
        "Anti dragon shield",
        "Anti panties",
        "Antisanta boots",
        "Antisanta gloves",
        "Antisanta jacket",
        "Antisanta mask",
        "Antisanta pantaloons",
        "Apprentice wand",
        "Arcane grimoire",
        "Arcane spirit shield",
        "Arceuus banner",
        "Arceuus hood",
        "Arceuus scarf",
        "Archer helm",
        "Archers ring",
        "Archers ring (i)",
        "Ardougne knight helm",
        "Ardougne max cape",
        "Ardougne max hood",
        "Armadyl bracers",
        "Armadyl chainskirt",
        "Armadyl chaps",
        "Armadyl chestplate",
        "Armadyl cloak",
        "Armadyl coif",
        "Armadyl crossbow",
        "Armadyl crozier",
        "Armadyl dhide body",
        "Armadyl dhide boots",
        "Armadyl dhide shield",
        "Armadyl full helm",
        "Armadyl godsword",
        "Armadyl godsword (or)",
        "Armadyl halo",
        "Armadyl helmet",
        "Armadyl helmet (or)",
        "Armadyl kiteshield",
        "Armadyl mitre",
        "Armadyl pendant",
        "Armadyl platebody",
        "Armadyl platelegs",
        "Armadyl plateskirt",
        "Armadyl robe legs",
        "Armadyl robe top",
        "Armadyl stole",
        "Assembler max cape",
        "Assembler max hood",
        "Assorted flowers",
        "Astral tiara",
        "Attack cape",
        "Attack hood",
        "Attacker icon",
        "Avas accumulator",
        "Avas assembler",
        "Avas attractor",
        "Avernic defender",
        "Axe handle",
        "Banana cape",
        "Banana hat",
        "Bandos boots",
        "Bandos boots (or)",
        "Bandos bracers",
        "Bandos chaps",
        "Bandos chestplate",
        "Bandos cloak",
        "Bandos coif",
        "Bandos crozier",
        "Bandos dhide body",
        "Bandos dhide boots",
        "Bandos dhide shield",
        "Bandos full helm",
        "Bandos godsword",
        "Bandos godsword (or)",
        "Bandos halo",
        "Bandos kiteshield",
        "Bandos mitre",
        "Bandos platebody",
        "Bandos platelegs",
        "Bandos plateskirt",
        "Bandos robe legs",
        "Bandos robe top",
        "Bandos stole",
        "Bandos tassets",
        "Bandos tassets (or)",
        "Banshee mask",
        "Banshee robe",
        "Banshee top",
        "Barb tail harpoon",
        "Barbed arrow",
        "Barbed bolts",
        "Barrelchest anchor",
        "Barronite mace",
        "Barrows gloves",
        "Battlestaff",
        "Beach boxing gloves",
        "Beacon ring",
        "Beads of the dead",
        "Bear feet",
        "Beekeepers boots",
        "Beekeepers gloves",
        "Beekeepers hat",
        "Beekeepers legs",
        "Beekeepers top",
        "Beginner wand",
        "Beret mask",
        "Berserker helm",
        "Berserker necklace",
        "Berserker ring",
        "Berserker ring (i)",
        "Big pirate hat",
        "Binding necklace",
        "Birthday balloons",
        "Birthday cake",
        "Black 2h sword",
        "Black axe",
        "Black battleaxe",
        "Black beret",
        "Black boater",
        "Black boots",
        "Black brutal",
        "Black cane",
        "Black cape",
        "Black cavalier",
        "Black chainbody",
        "Black chinchompa",
        "Black claws",
        "Black coffin",
        "Black dhide body",
        "Black dhide body (g)",
        "Black dhide body (t)",
        "Black dhide chaps",
        "Black dhide shield",
        "Black dagger",
        "Black dart",
        "Black defender",
        "Black demon mask",
        "Black desert robe",
        "Black desert shirt",
        "Black dragon mask",
        "Black elegant legs",
        "Black elegant shirt",
        "Black flowers",
        "Black full helm",
        "Black full helm (g)",
        "Black full helm (t)",
        "Black gloves",
        "Black hween mask",
        "Black halberd",
        "Black headband",
        "Black kiteshield",
        "Black kiteshield (g)",
        "Black kiteshield (t)",
        "Black knife",
        "Black leprechaun hat",
        "Black longsword",
        "Black mace",
        "Black mask",
        "Black mask (i)",
        "Black med helm",
        "Black naval shirt",
        "Black navy slacks",
        "Black partyhat",
        "Black pickaxe",
        "Black platebody",
        "Black platebody (g)",
        "Black platebody (t)",
        "Black platelegs",
        "Black platelegs (g)",
        "Black platelegs (t)",
        "Black plateskirt",
        "Black plateskirt (g)",
        "Black plateskirt (t)",
        "Black robe",
        "Black salamander",
        "Black santa hat",
        "Black satchel",
        "Black scimitar",
        "Black skirt",
        "Black skirt (g)",
        "Black skirt (t)",
        "Black slayer helmet",
        "Black spear",
        "Black spiky vambraces",
        "Black sq shield",
        "Black sword",
        "Black tricorn hat",
        "Black unicorn mask",
        "Black warhammer",
        "Black wizard hat (g)",
        "Black wizard hat (t)",
        "Black wizard robe (g)",
        "Black wizard robe (t)",
        "Blacksmiths helm",
        "Blade of saeldor",
        "Blade of saeldor (c)",
        "Blessed axe",
        "Blessed spirit shield",
        "Blisterwood flail",
        "Blisterwood sickle",
        "Blood tiara",
        "Bloodbark body",
        "Bloodbark boots",
        "Bloodbark gauntlets",
        "Bloodbark helm",
        "Bloodbark legs",
        "Blue beret",
        "Blue boater",
        "Blue boots",
        "Blue cape",
        "Blue dhide body",
        "Blue dhide body (g)",
        "Blue dhide body (t)",
        "Blue dhide chaps",
        "Blue dhide chaps (g)",
        "Blue dhide chaps (t)",
        "Blue dhide shield",
        "Blue dhide vambraces",
        "Blue dragon mask",
        "Blue elegant blouse",
        "Blue elegant legs",
        "Blue elegant shirt",
        "Blue elegant skirt",
        "Blue flowers",
        "Blue halloween mask",
        "Blue headband",
        "Blue icon",
        "Blue naval shirt",
        "Blue navy slacks",
        "Blue partyhat",
        "Blue robe bottoms",
        "Blue robe top",
        "Blue skirt",
        "Blue skirt (g)",
        "Blue skirt (t)",
        "Blue spiky vambraces",
        "Blue tricorn hat",
        "Blue wizard hat",
        "Blue wizard hat (g)",
        "Blue wizard hat (t)",
        "Blue wizard robe",
        "Blue wizard robe (g)",
        "Blue wizard robe (t)",
        "Blunt arrow",
        "Blurite bolts",
        "Blurite crossbow",
        "Blurite sword",
        "Bobs black shirt",
        "Bobs blue shirt",
        "Bobs green shirt",
        "Bobs purple shirt",
        "Bobs red shirt",
        "Bobble hat",
        "Bobble scarf",
        "Body tiara",
        "Bolt rack",
        "Bomber cap",
        "Bomber jacket",
        "Bone bolts",
        "Bone club",
        "Bone dagger",
        "Bone spear",
        "Bonecrusher necklace",
        "Book of balance",
        "Book of balance (or)",
        "Book of darkness",
        "Book of darkness (or)",
        "Book of law",
        "Book of law (or)",
        "Book of the dead",
        "Book of war",
        "Book of war (or)",
        "Boots of brimstone",
        "Boots of darkness",
        "Boots of lightness",
        "Boots of stone",
        "Boots of the eye",
        "Bow of faerdhinen",
        "Bow of faerdhinen (c)",
        "Boxing gloves",
        "Bracelet of clay",
        "Bracelet of ethereum",
        "Bracelet of slaughter",
        "Brass necklace",
        "Brassica halo",
        "Briefcase",
        "Brimstone ring",
        "Brine sabre",
        "Broad arrows",
        "Broad bolts",
        "Broken bark snelm",
        "Bronze 2h sword",
        "Bronze arrow",
        "Bronze axe",
        "Bronze battleaxe",
        "Bronze bolts",
        "Bronze boots",
        "Bronze brutal",
        "Bronze chainbody",
        "Bronze claws",
        "Bronze coffin",
        "Bronze crossbow",
        "Bronze dagger",
        "Bronze dart",
        "Bronze defender",
        "Bronze dragon mask",
        "Bronze fire arrow",
        "Bronze fist flag",
        "Bronze full helm",
        "Bronze full helm (g)",
        "Bronze full helm (t)",
        "Bronze gloves",
        "Bronze halberd",
        "Bronze hasta",
        "Bronze javelin",
        "Bronze kiteshield",
        "Bronze kiteshield (g)",
        "Bronze kiteshield (t)",
        "Bronze knife",
        "Bronze longsword",
        "Bronze mace",
        "Bronze med helm",
        "Bronze pickaxe",
        "Bronze platebody",
        "Bronze platebody (g)",
        "Bronze platebody (t)",
        "Bronze platelegs",
        "Bronze platelegs (g)",
        "Bronze platelegs (t)",
        "Bronze plateskirt",
        "Bronze plateskirt (g)",
        "Bronze plateskirt (t)",
        "Bronze scimitar",
        "Bronze spear",
        "Bronze sq shield",
        "Bronze sword",
        "Bronze thrownaxe",
        "Bronze warhammer",
        "Brown apron",
        "Brown headband",
        "Brown naval shirt",
        "Brown navy slacks",
        "Brown tricorn hat",
        "Bruma torch",
        "Bryophytas staff",
        "Bucket helm",
        "Bucket helm (g)",
        "Bug lantern",
        "Builders boots",
        "Builders shirt",
        "Builders trousers",
        "Bullet arrow",
        "Bunny ears",
        "Bunny feet",
        "Bunny legs",
        "Bunny paws",
        "Bunny top",
        "Bunnyman mask",
        "Burning amulet",
        "Butterfly net",
        "Cabbage cape",
        "Cabbage round shield",
        "Calamity breeches",
        "Calamity chest",
        "Camel mask",
        "Camo bottoms",
        "Camo helmet",
        "Candy cane",
        "Cap and goggles",
        "Cape of legends",
        "Cape of skulls",
        "Carnillean armour",
        "Carpenters boots",
        "Carpenters helmet",
        "Carpenters shirt",
        "Carpenters trousers",
        "Carrot sword",
        "Castle wars bracelet",
        "Cat training medal",
        "Catalytic tiara",
        "Catspeak amulet",
        "Cattleprod",
        "Cavalier mask",
        "Celestial ring",
        "Celestial signet",
        "Centurion cuirass",
        "Champions cape",
        "Chaos gauntlets",
        "Chaos tiara",
        "Chaotic handegg",
        "Chefs hat",
        "Chicken feet",
        "Chicken head",
        "Chicken legs",
        "Chicken wings",
        "Chinchompa",
        "Chronicle",
        "Circlet of water",
        "Citizen shoes",
        "Citizen top",
        "Citizen trousers",
        "Clan cloak",
        "Clan vexillum",
        "Clean necklace",
        "Climbing boots",
        "Climbing boots (g)",
        "Clown bow tie",
        "Clown gown",
        "Clown mask",
        "Clown shoes",
        "Clown trousers",
        "Clue hunter boots",
        "Clue hunter cloak",
        "Clue hunter garb",
        "Clue hunter gloves",
        "Clue hunter trousers",
        "Clueless scroll",
        "Collector icon",
        "Colossal blade",
        "Combat bracelet",
        "Comp ogre bow",
        "Cooking cape",
        "Cooking gauntlets",
        "Cooking hood",
        "Cormorants glove",
        "Corrupted axe",
        "Corrupted harpoon",
        "Corrupted helm",
        "Corrupted kiteshield",
        "Corrupted pickaxe",
        "Corrupted platebody",
        "Corrupted platelegs",
        "Corrupted plateskirt",
        "Corrupted sceptre",
        "Cosmic tiara",
        "Cow gloves",
        "Cow shoes",
        "Cow trousers",
        "Crab claw",
        "Crab helmet",
        "Crabclaw hook",
        "Crafting cape",
        "Crafting hood",
        "Crate ring",
        "Crate with zanik",
        "Craws bow",
        "Cream boots",
        "Cream hat",
        "Cream robe bottoms",
        "Cream robe top",
        "Crier bell",
        "Crier coat",
        "Crier hat",
        "Crone made amulet",
        "Cruciferous codex",
        "Crystal axe",
        "Crystal body",
        "Crystal bow",
        "Crystal bow (i)",
        "Crystal crown",
        "Crystal grail",
        "Crystal halberd",
        "Crystal halberd (i)",
        "Crystal harpoon",
        "Crystal helm",
        "Crystal legs",
        "Crystal pendant",
        "Crystal pickaxe",
        "Crystal sceptre",
        "Crystal shield",
        "Crystal shield (i)",
        "Cursed banana",
        "Cursed goblin bow",
        "Cursed goblin hammer",
        "Cursed goblin staff",
        "Cyclops head",
        "Dagonhai hat",
        "Dagonhai robe bottom",
        "Dagonhai robe top",
        "Dark bow tie",
        "Dark cavalier",
        "Dark dagger",
        "Dark flippers",
        "Dark infinity bottoms",
        "Dark infinity hat",
        "Dark infinity top",
        "Dark trousers",
        "Dark tuxedo cuffs",
        "Dark tuxedo jacket",
        "Dark tuxedo shoes",
        "Darklight",
        "Dawnbringer",
        "Deadmans cape",
        "Deadmans chest",
        "Deadmans legs",
        "Death tiara",
        "Decorative helm (red)",
        "Deerstalker",
        "Defence cape",
        "Defence hood",
        "Defender icon",
        "Defensive shield",
        "Demon feet",
        "Desert boots",
        "Desert camo legs",
        "Desert camo top",
        "Desert disguise",
        "Desert legs",
        "Desert robe",
        "Desert robes",
        "Desert shirt",
        "Desert top",
        "Devout boots",
        "Dharoks greataxe",
        "Dharoks helm",
        "Dharoks platebody",
        "Dharoks platelegs",
        "Diamond amulet",
        "Diamond bolts",
        "Diamond bolts (e)",
        "Diamond bracelet",
        "Diamond dragon bolts",
        "Diamond necklace",
        "Diamond ring",
        "Digsite pendant",
        "Dinhs bulwark",
        "Diving apparatus",
        "Diving helmet",
        "Doctors hat",
        "Dodgy necklace",
        "Dorgeshuun crossbow",
        "Double eye patch",
        "Dragon 2h sword",
        "Dragon arrow",
        "Dragon axe",
        "Dragon axe (or)",
        "Dragon battleaxe",
        "Dragon bolts",
        "Dragon boots",
        "Dragon boots (g)",
        "Dragon cane",
        "Dragon chainbody",
        "Dragon chainbody (g)",
        "Dragon claws",
        "Dragon claws (or)",
        "Dragon crossbow",
        "Dragon dagger",
        "Dragon dart",
        "Dragon defender",
        "Dragon defender (t)",
        "Dragon fire arrow",
        "Dragon full helm",
        "Dragon full helm (g)",
        "Dragon gloves",
        "Dragon halberd",
        "Dragon harpoon",
        "Dragon harpoon (or)",
        "Dragon hasta",
        "Dragon hunter lance",
        "Dragon javelin",
        "Dragon kiteshield",
        "Dragon kiteshield (g)",
        "Dragon knife",
        "Dragon longsword",
        "Dragon mace",
        "Dragon med helm",
        "Dragon necklace",
        "Dragon pickaxe",
        "Dragon pickaxe (or)",
        "Dragon platebody",
        "Dragon platebody (g)",
        "Dragon platelegs",
        "Dragon platelegs (g)",
        "Dragon plateskirt",
        "Dragon plateskirt (g)",
        "Dragon scimitar",
        "Dragon scimitar (or)",
        "Dragon spear",
        "Dragon sq shield",
        "Dragon sq shield (g)",
        "Dragon sword",
        "Dragon thrownaxe",
        "Dragon warhammer",
        "Dragon warhammer (or)",
        "Dragonbone necklace",
        "Dragonfire shield",
        "Dragonfire ward",
        "Dragonstone amulet",
        "Dragonstone bolts",
        "Dragonstone bolts (e)",
        "Dragonstone boots",
        "Dragonstone bracelet",
        "Dragonstone full helm",
        "Dragonstone gauntlets",
        "Dragonstone platebody",
        "Dragonstone platelegs",
        "Dragonstone ring",
        "Drakans medallion",
        "Dramen staff",
        "Druids robe",
        "Druids robe top",
        "Druidic wreath",
        "Dust battlestaff",
        "Dwarven helmet",
        "Eagle cape",
        "Earth battlestaff",
        "Earth tiara",
        "Easter basket",
        "Easter blaster",
        "Easter egg helm",
        "Easter hat",
        "Easter ring",
        "Efaritays aid",
        "Egg whisk",
        "Eggshell platebody",
        "Eggshell platelegs",
        "Elder chaos hood",
        "Elder chaos hood (or)",
        "Elder chaos robe",
        "Elder chaos robe (or)",
        "Elder chaos top",
        "Elder chaos top (or)",
        "Elder maul",
        "Elder wand",
        "Elemental helmet",
        "Elemental shield",
        "Elemental tiara",
        "Elidinis broken ward",
        "Elidinis ward",
        "Elite calamity chest",
        "Elite void robe",
        "Elite void robe (or)",
        "Elite void top",
        "Elite void top (or)",
        "Elven boots",
        "Elven gloves",
        "Elven legwear",
        "Elven signet",
        "Elven skirt (white)",
        "Elven skirt (yellow)",
        "Elven top (white)",
        "Elven top (yellow)",
        "Elysian spirit shield",
        "Emerald amulet",
        "Emerald bolts",
        "Emerald bolts (e)",
        "Emerald bracelet",
        "Emerald dragon bolts",
        "Emerald necklace",
        "Emerald ring",
        "Emerald sickle (b)",
        "Empty blaster",
        "Enchanted hat",
        "Enchanted lyre",
        "Enchanted lyre(i)",
        "Enchanted robe",
        "Enchanted top",
        "Eternal boots",
        "Event rpg",
        "Evil chicken feet",
        "Evil chicken head",
        "Evil chicken legs",
        "Evil chicken wings",
        "Excalibur",
        "Expeditious bracelet",
        "Expert mining gloves",
        "Explorer backpack",
        "Extradimensional bag",
        "Fairy mushroom",
        "Fake beak",
        "Falconers glove",
        "Fancy boots",
        "Fancy tiara",
        "Farmers boots",
        "Farmers jacket",
        "Farmers shirt",
        "Farmers strawhat",
        "Farming cape",
        "Farming hood",
        "Farseer helm",
        "Ferocious gloves",
        "Festive elf hat",
        "Festive elf slippers",
        "Field arrow",
        "Fighter hat",
        "Fighter torso",
        "Fighting boots",
        "Fine mesh net",
        "Fire battlestaff",
        "Fire cape",
        "Fire max cape",
        "Fire max hood",
        "Fire tiara",
        "Firemaking cape",
        "Firemaking hood",
        "Fish sack",
        "Fish sack barrel",
        "Fishbowl helmet",
        "Fishing cape",
        "Fishing hood",
        "Five barrels",
        "Fixed device",
        "Flamtaer bracelet",
        "Flared trousers",
        "Fletching cape",
        "Fletching hood",
        "Four barrels",
        "Fremennik beige shirt",
        "Fremennik black cloak",
        "Fremennik blade",
        "Fremennik blue cloak",
        "Fremennik blue shirt",
        "Fremennik boots",
        "Fremennik brown cloak",
        "Fremennik brown shirt",
        "Fremennik cyan cloak",
        "Fremennik gloves",
        "Fremennik green cloak",
        "Fremennik grey cloak",
        "Fremennik grey shirt",
        "Fremennik hat",
        "Fremennik helm",
        "Fremennik kilt",
        "Fremennik pink cloak",
        "Fremennik red cloak",
        "Fremennik red shirt",
        "Fremennik robe",
        "Fremennik shield",
        "Fremennik skirt",
        "Fremennik teal cloak",
        "Frog mask",
        "Frog slippers",
        "Frog leather body",
        "Frog leather boots",
        "Frog leather chaps",
        "Frozen abyssal whip",
        "Frying pan",
        "Gadderhammer",
        "Games necklace",
        "Gardening boots",
        "Gauntlet cape",
        "Ghostly boots",
        "Ghostly cloak",
        "Ghostly gloves",
        "Ghostly hood",
        "Ghostly robe (bottom)",
        "Ghostly robe (top)",
        "Ghostspeak amulet",
        "Ghrazi rapier",
        "Giant boot",
        "Giant boulder",
        "Giant easter egg",
        "Giant present",
        "Gilded 2h sword",
        "Gilded axe",
        "Gilded boots",
        "Gilded chainbody",
        "Gilded coif",
        "Gilded dhide body",
        "Gilded dhide chaps",
        "Gilded full helm",
        "Gilded hasta",
        "Gilded kiteshield",
        "Gilded med helm",
        "Gilded pickaxe",
        "Gilded platebody",
        "Gilded platelegs",
        "Gilded plateskirt",
        "Gilded scimitar",
        "Gilded smile flag",
        "Gilded spade",
        "Gilded spear",
        "Gilded sq shield",
        "Gingerbread shield",
        "Glarials amulet",
        "Gloves of darkness",
        "Gloves of silence",
        "Glowing dagger",
        "Gnome amulet",
        "Gnome child hat",
        "Gnome child mask",
        "Gnome goggles",
        "Gnome scarf",
        "Gnomeball",
        "Goblin mask",
        "Gold amulet",
        "Gold bracelet",
        "Gold coffin",
        "Gold elegant blouse",
        "Gold elegant legs",
        "Gold elegant shirt",
        "Gold elegant skirt",
        "Gold headband",
        "Gold helmet",
        "Gold necklace",
        "Gold ring",
        "Gold satchel",
        "Gold tiara",
        "Golden apron",
        "Golden chefs hat",
        "Golden tench",
        "Goldsmith gauntlets",
        "Gorilla greegree",
        "Graahk headdress",
        "Graahk legs",
        "Graahk top",
        "Graceful boots",
        "Graceful cape",
        "Graceful gloves",
        "Graceful hood",
        "Graceful legs",
        "Graceful top",
        "Granite body",
        "Granite boots",
        "Granite gloves",
        "Granite hammer",
        "Granite helm",
        "Granite legs",
        "Granite longsword",
        "Granite maul",
        "Granite maul (or)",
        "Granite ring",
        "Granite ring (i)",
        "Granite shield",
        "Gravedigger boots",
        "Gravedigger gloves",
        "Gravedigger leggings",
        "Gravedigger mask",
        "Gravedigger top",
        "Greater demon mask",
        "Green banner",
        "Green boater",
        "Green boots",
        "Green cape",
        "Green dhide body",
        "Green dhide body (g)",
        "Green dhide body (t)",
        "Green dhide chaps",
        "Green dhide shield",
        "Green dragon mask",
        "Green elegant blouse",
        "Green elegant legs",
        "Green elegant shirt",
        "Green elegant skirt",
        "Green halloween mask",
        "Green hat",
        "Green headband",
        "Green naval shirt",
        "Green navy slacks",
        "Green partyhat",
        "Green robe bottoms",
        "Green robe top",
        "Green satchel",
        "Green slayer helmet",
        "Green spiky vambraces",
        "Green tricorn hat",
        "Greggs eastdoor",
        "Grey boots",
        "Grey gloves",
        "Grey naval shirt",
        "Grey navy slacks",
        "Grey robe bottoms",
        "Grey robe top",
        "Grey tricorn hat",
        "Grim reaper hood",
        "Group iron bracers",
        "Group iron helm",
        "Group iron platebody",
        "Group iron platelegs",
        "Guardian boots",
        "Guthans chainskirt",
        "Guthans helm",
        "Guthans platebody",
        "Guthans warspear",
        "Guthix bracers",
        "Guthix cape",
        "Guthix chaps",
        "Guthix cloak",
        "Guthix coif",
        "Guthix crozier",
        "Guthix dhide body",
        "Guthix dhide boots",
        "Guthix dhide shield",
        "Guthix full helm",
        "Guthix halo",
        "Guthix kiteshield",
        "Guthix max cape",
        "Guthix max hood",
        "Guthix mitre",
        "Guthix mjolnir",
        "Guthix platebody",
        "Guthix platelegs",
        "Guthix plateskirt",
        "Guthix robe legs",
        "Guthix robe top",
        "Guthix staff",
        "Guthix stole",
        "Half moon spectacles",
        "Hallowed focus",
        "Hallowed grapple",
        "Hallowed hammer",
        "Hallowed ring",
        "Hallowed symbol",
        "Ham boots",
        "Ham cloak",
        "Ham gloves",
        "Ham joint",
        "Ham shirt",
        "Hard leather shield",
        "Hardcore ironman helm",
        "Hardleather body",
        "Hardleather gloves",
        "Harralander tar",
        "Harrys cutlass",
        "Hat eyepatch",
        "Hat of the eye",
        "Haunted wine bottle",
        "Hazeels mark",
        "Headless head",
        "Healer hat",
        "Healer icon",
        "Heat proof vessel",
        "Heavy ballista",
        "Heavy ballista (or)",
        "Heavy casket",
        "Hell cat ears",
        "Helm of neitiznot",
        "Helm of raedwald",
        "Herblore cape",
        "Herblore hood",
        "Highwayman mask",
        "Hill giant club",
        "Hitpoints cape",
        "Hitpoints hood",
        "Holy blessing",
        "Holy book",
        "Holy book (or)",
        "Holy ghrazi rapier",
        "Holy handegg",
        "Holy sandals",
        "Holy scythe of vitur",
        "Holy symbol",
        "Holy water",
        "Holy wraps",
        "Honourable blessing",
        "Hood of darkness",
        "Hooded cloak",
        "Hornwood helm",
        "Hosidius banner",
        "Hosidius hood",
        "Hosidius scarf",
        "Hunter cape",
        "Hunter hood",
        "Hunters honour",
        "Hunters crossbow",
        "Hunting knife",
        "Hydra slayer helmet",
        "Ibans staff",
        "Ibans staff (u)",
        "Ice arrows",
        "Ice gloves",
        "Imbued guthix cape",
        "Imbued saradomin cape",
        "Imbued tephra",
        "Imbued zamorak cape",
        "Imcando hammer",
        "Incomplete blaster",
        "Infernal axe",
        "Infernal axe (or)",
        "Infernal cape",
        "Infernal harpoon",
        "Infernal harpoon (or)",
        "Infernal max cape",
        "Infernal max hood",
        "Infernal pickaxe",
        "Infernal pickaxe (or)",
        "Infinity boots",
        "Infinity bottoms",
        "Infinity gloves",
        "Infinity hat",
        "Infinity top",
        "Initiate cuisse",
        "Initiate hauberk",
        "Initiate sallet",
        "Inoculation bracelet",
        "Inquisitors hauberk",
        "Inquisitors mace",
        "Insulated boots",
        "Inverted santa hat",
        "Iron 2h sword",
        "Iron arrow",
        "Iron battleaxe",
        "Iron bolts",
        "Iron boots",
        "Iron brutal",
        "Iron chainbody",
        "Iron claws",
        "Iron crossbow",
        "Iron dagger",
        "Iron dart",
        "Iron defender",
        "Iron dragon mask",
        "Iron fire arrow",
        "Iron full helm",
        "Iron full helm (g)",
        "Iron full helm (t)",
        "Iron gloves",
        "Iron halberd",
        "Iron hasta",
        "Iron javelin",
        "Iron kiteshield",
        "Iron kiteshield (g)",
        "Iron kiteshield (t)",
        "Iron knife",
        "Iron longsword",
        "Iron mace",
        "Iron med helm",
        "Iron pickaxe",
        "Iron pickaxe (nz)",
        "Iron platebody",
        "Iron platebody (g)",
        "Iron platebody (t)",
        "Iron platelegs",
        "Iron platelegs (g)",
        "Iron platelegs (t)",
        "Iron plateskirt",
        "Iron plateskirt (g)",
        "Iron plateskirt (t)",
        "Iron scimitar",
        "Iron sickle",
        "Iron spear",
        "Iron sq shield",
        "Iron sword",
        "Iron thrownaxe",
        "Iron warhammer",
        "Ironman helm",
        "Ironman platebody",
        "Ironman platelegs",
        "Ivandis flail",
        "Jack lantern mask",
        "Jade amulet",
        "Jade bolts",
        "Jade bolts (e)",
        "Jade bracelet",
        "Jade dragon bolts",
        "Jade dragon bolts (e)",
        "Jade machete",
        "Jade necklace",
        "Jade ring",
        "Jester cape",
        "Jester hat",
        "Jester scarf",
        "Jonas mask",
        "Jungle camo legs",
        "Jungle camo top",
        "Jungle demon mask",
        "Justiciar chestguard",
        "Justiciar faceguard",
        "Justiciar legguards",
        "Karils coif",
        "Karils crossbow",
        "Karils leatherskirt",
        "Karils leathertop",
        "Kebbit bolts",
        "Keris partisan",
        "Kharedsts memoirs",
        "Khazard armour",
        "Khazard helmet",
        "Killers knife",
        "Kitchen knife",
        "Klanks gauntlets",
        "Kodai wand",
        "Koriffs coif",
        "Koriffs cowl",
        "Koriffs headband",
        "Kruk monkey greegree",
        "Kyatt hat",
        "Kyatt legs",
        "Kyatt top",
        "Large spade",
        "Larupia hat",
        "Larupia legs",
        "Larupia top",
        "Lathas amulet",
        "Lava battlestaff",
        "Lava battlestaff (or)",
        "Lava dragon mask",
        "Law tiara",
        "Leaf bladed battleaxe",
        "Leaf bladed spear",
        "Leaf bladed sword",
        "Leather body",
        "Leather body (g)",
        "Leather boots",
        "Leather chaps",
        "Leather chaps (g)",
        "Leather cowl",
        "Leather gloves",
        "Leather vambraces",
        "Lederhosen hat",
        "Lederhosen shorts",
        "Lederhosen top",
        "Left eye patch",
        "Leprechaun hat",
        "Lesser demon mask",
        "Light ballista",
        "Light bow tie",
        "Light infinity hat",
        "Light infinity top",
        "Light trousers",
        "Light tuxedo cuffs",
        "Light tuxedo jacket",
        "Light tuxedo shoes",
        "Lightbearer",
        "Long kebbit bolts",
        "Lovakengj banner",
        "Lovakengj hood",
        "Lovakengj scarf",
        "Lucky cutlass",
        "Lucky shot flag",
        "Lumberjack boots",
        "Lumberjack hat",
        "Lumberjack legs",
        "Lumberjack top",
        "Lunar amulet",
        "Lunar boots",
        "Lunar cape",
        "Lunar gloves",
        "Lunar helm",
        "Lunar legs",
        "Lunar ring",
        "Lunar staff",
        "Lunar torso",
        "Mspeak amulet",
        "Mages book",
        "Magic butterfly net",
        "Magic cape",
        "Magic comp bow",
        "Magic hood",
        "Magic longbow",
        "Magic secateurs",
        "Magic secateurs (nz)",
        "Magic shield",
        "Magic shortbow",
        "Magic shortbow (i)",
        "Magic staff",
        "Magma helm",
        "Malediction ward",
        "Malediction ward (or)",
        "Man speak amulet",
        "Maomas full helm",
        "Maomas great helm",
        "Maomas med helm",
        "Maple blackjack",
        "Maple blackjack(d)",
        "Maple blackjack(o)",
        "Maple longbow",
        "Maple shield",
        "Maple shortbow",
        "Marrentill tar",
        "Mask of balance",
        "Mask of ranul",
        "Masori amulet",
        "Masori chainskirt",
        "Masori chestplate",
        "Masori headdress",
        "Master wand",
        "Meat tenderiser",
        "Medical gown",
        "Menaphite purple hat",
        "Menaphite purple kilt",
        "Menaphite purple robe",
        "Menaphite purple top",
        "Menaphite red hat",
        "Menaphite red kilt",
        "Menaphite red robe",
        "Menaphite red top",
        "Merfolk trident",
        "Mime boots",
        "Mime gloves",
        "Mime legs",
        "Mime mask",
        "Mind helmet",
        "Mind shield",
        "Mind tiara",
        "Mining cape",
        "Mining gloves",
        "Mining helmet",
        "Mining hood",
        "Mirror shield",
        "Mist battlestaff",
        "Mith grapple",
        "Mithril 2h sword",
        "Mithril arrow",
        "Mithril axe",
        "Mithril battleaxe",
        "Mithril bolts",
        "Mithril boots",
        "Mithril brutal",
        "Mithril chainbody",
        "Mithril claws",
        "Mithril crossbow",
        "Mithril dagger",
        "Mithril dart",
        "Mithril defender",
        "Mithril dragon mask",
        "Mithril fire arrow",
        "Mithril full helm",
        "Mithril full helm (g)",
        "Mithril full helm (t)",
        "Mithril gloves",
        "Mithril halberd",
        "Mithril hasta",
        "Mithril javelin",
        "Mithril kiteshield",
        "Mithril knife",
        "Mithril longsword",
        "Mithril mace",
        "Mithril med helm",
        "Mithril pickaxe",
        "Mithril pickaxe (nz)",
        "Mithril platebody",
        "Mithril platebody (g)",
        "Mithril platebody (t)",
        "Mithril platelegs",
        "Mithril platelegs (g)",
        "Mithril platelegs (t)",
        "Mithril plateskirt",
        "Mithril scimitar",
        "Mithril spear",
        "Mithril sq shield",
        "Mithril sword",
        "Mithril thrownaxe",
        "Mithril warhammer",
        "Mixed flowers",
        "Mole slippers",
        "Monks robe",
        "Monks robe (g)",
        "Monks robe (t)",
        "Monks robe top",
        "Monks robe top (g)",
        "Monks robe top (t)",
        "Monkey talisman",
        "Moonclan armour",
        "Moonclan boots",
        "Moonclan cape",
        "Moonclan gloves",
        "Moonclan hat",
        "Moonclan helm",
        "Moonclan skirt",
        "Morrigans coif",
        "Morrigans javelin",
        "Mourner boots",
        "Mourner cloak",
        "Mourner gloves",
        "Mourner top",
        "Mourner trousers",
        "Mouse toy",
        "Mouth grip",
        "Mud battlestaff",
        "Mudskipper hat",
        "Mummys body",
        "Mummys feet",
        "Mummys hands",
        "Mummys head",
        "Mummys legs",
        "Music cape",
        "Music hood",
        "Musketeer hat",
        "Musketeer pants",
        "Musketeer tabard",
        "Myre snelm (pointed)",
        "Myre snelm (round)",
        "Mystic air staff",
        "Mystic boots",
        "Mystic boots (dark)",
        "Mystic boots (dusk)",
        "Mystic boots (light)",
        "Mystic boots (or)",
        "Mystic dust staff",
        "Mystic earth staff",
        "Mystic fire staff",
        "Mystic gloves",
        "Mystic gloves (dark)",
        "Mystic gloves (dusk)",
        "Mystic gloves (light)",
        "Mystic gloves (or)",
        "Mystic hat",
        "Mystic hat (dark)",
        "Mystic hat (dusk)",
        "Mystic hat (light)",
        "Mystic hat (or)",
        "Mystic lava staff",
        "Mystic mist staff",
        "Mystic mud staff",
        "Mystic robe bottom",
        "Mystic robe top",
        "Mystic robe top (or)",
        "Mystic smoke staff",
        "Mystic steam staff",
        "Mystic water staff",
        "Mythical cape",
        "Mythical max cape",
        "Mythical max hood",
        "Nature tiara",
        "Navy cavalier",
        "Necklace of anguish",
        "Necklace of faith",
        "Necklace of passage",
        "Neitiznot faceguard",
        "Neitiznot shield",
        "Nightmare staff",
        "Noose wand",
        "Null amulet",
        "Nurse hat",
        "Oak blackjack",
        "Oak blackjack(d)",
        "Oak blackjack(o)",
        "Oak longbow",
        "Oak shield",
        "Oak shortbow",
        "Obsidian cape",
        "Obsidian cape (r)",
        "Obsidian helmet",
        "Obsidian platebody",
        "Obsidian platelegs",
        "Occult necklace",
        "Occult necklace (or)",
        "Ochre snelm (pointed)",
        "Ochre snelm (round)",
        "Odd spectacles",
        "Odium ward",
        "Odium ward (or)",
        "Ogre arrow",
        "Old demon mask",
        "One barrel",
        "Onyx amulet",
        "Onyx bolts",
        "Onyx bolts (e)",
        "Onyx bracelet",
        "Onyx dragon bolts",
        "Onyx dragon bolts (e)",
        "Onyx necklace",
        "Onyx ring",
        "Opal amulet",
        "Opal bolts",
        "Opal bolts (e)",
        "Opal bracelet",
        "Opal dragon bolts",
        "Opal dragon bolts (e)",
        "Opal machete",
        "Opal necklace",
        "Opal ring",
        "Orange boater",
        "Orange cape",
        "Orange flowers",
        "Orange salamander",
        "Ornate boots",
        "Ornate cape",
        "Ornate gloves",
        "Ornate helm",
        "Ornate legs",
        "Ornate top",
        "Osmumtens fang",
        "Pantaloons",
        "Partyhat & specs",
        "Peaceful blessing",
        "Peaceful handegg",
        "Pearl barbarian rod",
        "Pearl bolts",
        "Pearl bolts (e)",
        "Pearl dragon bolts",
        "Pearl fishing rod",
        "Pearl fly fishing rod",
        "Pegasian boots",
        "Penance gloves",
        "Penance skirt",
        "Pendant of lucien",
        "Penguin mask",
        "perfect necklace",
        "perfect ring",
        "Pharaohs sceptre",
        "Phasmatys flag",
        "Phoenix crossbow",
        "Phoenix necklace",
        "Pickaxe handle",
        "Pink boater",
        "Pink boots",
        "Pink cape",
        "Pink elegant blouse",
        "Pink elegant legs",
        "Pink elegant shirt",
        "Pink elegant skirt",
        "Pink headband",
        "Pink robe bottoms",
        "Pink robe top",
        "Pink skirt",
        "Pirate bandana (blue)",
        "Pirate bandana (red)",
        "Pirate boots",
        "Pirate hat",
        "Pirate hat & patch",
        "Pirate leggings (red)",
        "Pirates hat",
        "Pirates hook",
        "Piscarilius banner",
        "Piscarilius hood",
        "Piscarilius scarf",
        "Pith helmet",
        "Plague jacket",
        "Plague trousers",
        "Plain satchel",
        "Poisoned dart(p)",
        "Polar camo legs",
        "Polar camo top",
        "Portable waystone",
        "Prayer cape",
        "Prayer hood",
        "Pre nature amulet",
        "Priest gown (bottom)",
        "Priest gown (top)",
        "Primordial boots",
        "Prince leggings",
        "Prince tunic",
        "Princely monkey",
        "Princess blouse",
        "Princess skirt",
        "Progress hat",
        "Prop sword",
        "Propeller hat",
        "Proselyte cuisse",
        "Proselyte hauberk",
        "Proselyte sallet",
        "Proselyte tasset",
        "Prospector boots",
        "Prospector helmet",
        "Prospector jacket",
        "Prospector legs",
        "Protest banner",
        "Pumpkin lantern",
        "Purple boater",
        "Purple boots",
        "Purple cape",
        "Purple elegant blouse",
        "Purple elegant legs",
        "Purple elegant shirt",
        "Purple elegant skirt",
        "Purple flowers",
        "Purple gloves",
        "Purple hat",
        "Purple naval shirt",
        "Purple navy slacks",
        "Purple partyhat",
        "Purple robe bottoms",
        "Purple robe top",
        "Purple slayer helmet",
        "Purple tricorn hat",
        "Pyromancer boots",
        "Pyromancer garb",
        "Pyromancer hood",
        "Pyromancer robe",
        "Quest point cape",
        "Quest point hood",
        "Rainbow flower crown",
        "Rainbow partyhat",
        "Rainbow scarf",
        "Ram skull helm",
        "Ranger boots",
        "Ranger gloves",
        "Ranger hat",
        "Rangers tights",
        "Rangers tunic",
        "Ranging cape",
        "Ranging hood",
        "Red beret",
        "Red boater",
        "Red boots",
        "Red cape (Soul Wars)",
        "Red cavalier",
        "Red chinchompa",
        "Red dhide body",
        "Red dhide body (g)",
        "Red dhide body (t)",
        "Red dhide chaps",
        "Red dhide chaps (g)",
        "Red dhide chaps (t)",
        "Red dhide shield",
        "Red dhide vambraces",
        "Red dragon mask",
        "Red elegant blouse",
        "Red elegant legs",
        "Red elegant shirt",
        "Red elegant skirt",
        "Red flowers",
        "Red gloves",
        "Red halloween mask",
        "Red headband",
        "Red naval shirt",
        "Red navy slacks",
        "Red partyhat",
        "Red robe bottoms",
        "Red robe top",
        "Red salamander",
        "Red satchel",
        "Red slayer helmet",
        "Red slayer helmet (i)",
        "Red spiky vambraces",
        "Red topaz machete",
        "Red tricorn hat",
        "Redwood shield",
        "Regen bracelet",
        "Reindeer hat",
        "Reinforced goggles",
        "Right eye patch",
        "Ring of charos",
        "Ring of coins",
        "Ring of dueling",
        "Ring of endurance",
        "Ring of forging",
        "Ring of life",
        "Ring of nature",
        "Ring of pursuit",
        "Ring of recoil",
        "Ring of returning",
        "Ring of stone",
        "Ring of suffering",
        "Ring of suffering (i)",
        "Ring of the elements",
        "Ring of the gods",
        "Ring of the gods (i)",
        "Ring of visibility",
        "Ring of wealth",
        "Ring of wealth (i)",
        "Robe top of darkness",
        "Robe top of the eye",
        "Robin hood hat",
        "Rock shell boots",
        "Rock shell gloves",
        "Rock shell helm",
        "Rock shell legs",
        "Rock shell plate",
        "Rod of ivandis",
        "Rogue boots",
        "Rogue gloves",
        "Rogue mask",
        "Rogue top",
        "Rogue trousers",
        "Rogues revenge",
        "Rolling pin",
        "Royal crown",
        "Royal gown bottom",
        "Royal gown top",
        "Royal sceptre",
        "Rubber chicken",
        "Ruby amulet",
        "Ruby bolts",
        "Ruby bolts (e)",
        "Ruby bracelet",
        "Ruby dragon bolts",
        "Ruby dragon bolts (e)",
        "Ruby necklace",
        "Ruby ring",
        "Ruby sickle (b)",
        "Rune 2h sword",
        "Rune arrow",
        "Rune battleaxe",
        "Rune boots",
        "Rune brutal",
        "Rune cane",
        "Rune chainbody",
        "Rune claws",
        "Rune crossbow",
        "Rune crossbow (or)",
        "Rune dagger",
        "Rune dart",
        "Rune defender",
        "Rune defender (t)",
        "Rune dragon mask",
        "Rune fire arrow",
        "Rune full helm",
        "Rune full helm (g)",
        "Rune full helm (t)",
        "Rune gloves",
        "Rune gloves (wrapped)",
        "Rune halberd",
        "Rune hasta",
        "Rune javelin",
        "Rune kiteshield",
        "Rune kiteshield (g)",
        "Rune kiteshield (HAM)",
        "Rune kiteshield (t)",
        "Rune knife",
        "Rune longsword",
        "Rune mace",
        "Rune med helm",
        "Rune pickaxe",
        "Rune pickaxe (nz)",
        "Rune platebody",
        "Rune platebody (g)",
        "Rune platebody (t)",
        "Rune platelegs",
        "Rune platelegs (g)",
        "Rune platelegs (t)",
        "Rune plateskirt",
        "Rune plateskirt (g)",
        "Rune plateskirt (t)",
        "Rune satchel",
        "Rune scimitar",
        "Rune spear",
        "Rune sq shield",
        "Rune sword",
        "Rune thrownaxe",
        "Rune warhammer",
        "Runecraft cape",
        "Runecraft hood",
        "Runefest shield",
        "Runite bolts",
        "Runner boots",
        "Runner hat",
        "Sack of presents",
        "Sagacious spectacles",
        "Saikas hood",
        "Saikas shroud",
        "Saikas veil",
        "Salve amulet",
        "Salve amulet (e)",
        "Salve amulet(ei)",
        "Salve amulet(i)",
        "Samurai boots",
        "Samurai gloves",
        "Samurai greaves",
        "Samurai kasa",
        "Samurai shirt",
        "Sandwich lady bottom",
        "Sandwich lady hat",
        "Sandwich lady top",
        "Sanguinesti staff",
        "Santa boots",
        "Santa gloves",
        "Santa hat",
        "Santa jacket",
        "Santa mask",
        "Santa pantaloons",
        "Sapphire amulet",
        "Sapphire bolts",
        "Sapphire bolts (e)",
        "Sapphire bracelet",
        "Sapphire dragon bolts",
        "Sapphire necklace",
        "Sapphire ring",
        "Sarachnis cudgel",
        "Saradomin banner",
        "Saradomin bracers",
        "Saradomin cape",
        "Saradomin chaps",
        "Saradomin cloak",
        "Saradomin coif",
        "Saradomin crozier",
        "Saradomin dhide body",
        "Saradomin full helm",
        "Saradomin godsword",
        "Saradomin halo",
        "Saradomin kiteshield",
        "Saradomin max cape",
        "Saradomin max hood",
        "Saradomin mitre",
        "Saradomin mjolnir",
        "Saradomin platebody",
        "Saradomin platelegs",
        "Saradomin plateskirt",
        "Saradomin robe legs",
        "Saradomin robe top",
        "Saradomin staff",
        "Saradomin stole",
        "Saradomin sword",
        "Scroll sack",
        "Scythe of vitur",
        "Seal of passage",
        "Secret santa present",
        "Seers ring",
        "Seers ring (i)",
        "Seren halo",
        "Serpentine helm",
        "Severed leg",
        "Shade robe",
        "Shade robe top",
        "Shadow of tumeken",
        "Shadow sword",
        "Shaman mask",
        "Shattered banner",
        "Shattered cane",
        "Shayzien banner",
        "Shayzien hood",
        "Shayzien scarf",
        "Shirt (brown)",
        "Shirt (lilac)",
        "Shirt (yellow)",
        "Shorts (blue)",
        "Shorts (brown)",
        "Shorts (yellow)",
        "Shoulder parrot",
        "Signed oak bow",
        "Silly jester boots",
        "Silly jester hat",
        "Silly jester tights",
        "Silly jester top",
        "Silver bolts",
        "Silver coffin",
        "Silver necklace",
        "Silver sickle",
        "Silver sickle (b)",
        "Silverlight",
        "Sirens tome",
        "Skeletal boots",
        "Skeletal bottoms",
        "Skeletal gloves",
        "Skeletal helm",
        "Skeletal top",
        "Skeleton boots",
        "Skeleton gloves",
        "Skeleton lantern",
        "Skeleton leggings",
        "Skeleton mask",
        "Skeleton shirt",
        "Skills necklace",
        "Skirt (blue)",
        "Skirt (brown)",
        "Skirt (lilac)",
        "Skull sceptre",
        "Skull sceptre (i)",
        "Slave boots",
        "Slave robe",
        "Slave shirt",
        "Slayer cape",
        "Slayer gloves",
        "Slayer helmet",
        "Slayer helmet (i)",
        "Slayer hood",
        "Slayer ring",
        "Slayer ring (eternal)",
        "Slayers staff",
        "Slayers staff (e)",
        "Sleeping cap",
        "Smithing cape",
        "Smithing hood",
        "Smiths boots",
        "Smiths gloves",
        "Smiths gloves (i)",
        "Smiths trousers",
        "Smiths tunic",
        "Smoke battlestaff",
        "Snakeskin bandana",
        "Snakeskin body",
        "Snakeskin boots",
        "Snakeskin chaps",
        "Snakeskin shield",
        "Snakeskin vambraces",
        "Snow imp costume body",
        "Snow imp costume feet",
        "Snow imp costume head",
        "Snow imp costume legs",
        "Snow imp costume tail",
        "Snowman ring",
        "Soul cape",
        "Soul tiara",
        "Spiked manacles",
        "Spiky vambraces",
        "Spined body",
        "Spined boots",
        "Spined chaps",
        "Spined gloves",
        "Spined helm",
        "Spiny helmet",
        "Spirit angler boots",
        "Spirit angler top",
        "Spirit angler waders",
        "Spirit shield",
        "Splitbark body",
        "Splitbark boots",
        "Splitbark gauntlets",
        "Splitbark helm",
        "Splitbark legs",
        "Spookier boots",
        "Spookier gloves",
        "Spookier hood",
        "Spookier robe",
        "Spookier skirt",
        "Spooky boots",
        "Spooky gloves",
        "Spooky hood",
        "Spooky robe",
        "Spooky skirt",
        "Spotted cape",
        "Spottier cape",
        "Staff of air",
        "Staff of balance",
        "Staff of bob the cat",
        "Staff of earth",
        "Staff of fire",
        "Staff of light",
        "Staff of the dead",
        "Staff of water",
        "Stale baguette",
        "Star face",
        "Starter bow",
        "Starter staff",
        "Starter sword",
        "Statiuss full helm",
        "Statiuss platebody",
        "Statiuss platelegs",
        "Statiuss warhammer",
        "Steam battlestaff",
        "Steel 2h sword",
        "Steel arrow",
        "Steel axe",
        "Steel battleaxe",
        "Steel bolts",
        "Steel boots",
        "Steel brutal",
        "Steel chainbody",
        "Steel claws",
        "Steel coffin",
        "Steel crossbow",
        "Steel dagger",
        "Steel dart",
        "Steel defender",
        "Steel dragon mask",
        "Steel fire arrow",
        "Steel full helm",
        "Steel full helm (g)",
        "Steel full helm (t)",
        "Steel gauntlets",
        "Steel gloves",
        "Steel halberd",
        "Steel hasta",
        "Steel javelin",
        "Steel kiteshield",
        "Steel kiteshield (g)",
        "Steel kiteshield (t)",
        "Steel knife",
        "Steel longsword",
        "Steel mace",
        "Steel med helm",
        "Steel pickaxe",
        "Steel platebody",
        "Steel platebody (g)",
        "Steel platebody (t)",
        "Steel platelegs",
        "Steel platelegs (g)",
        "Steel platelegs (t)",
        "Steel plateskirt",
        "Steel plateskirt (g)",
        "Steel plateskirt (t)",
        "Steel scimitar",
        "Steel spear",
        "Steel sq shield",
        "Steel sword",
        "Steel thrownaxe",
        "Steel warhammer",
        "Strength amulet (t)",
        "Strength cape",
        "Strength hood",
        "Strung rabbit foot",
        "Studded body",
        "Studded body (g)",
        "Studded body (t)",
        "Studded chaps",
        "Studded chaps (g)",
        "Studded chaps (t)",
        "Swamp lizard",
        "Swampbark body",
        "Swampbark boots",
        "Swampbark gauntlets",
        "Swampbark helm",
        "Swampbark legs",
        "Swift blade",
        "Tan cavalier",
        "Tanzanite helm",
        "Tarnished locket",
        "Tarromin tar",
        "Teacher wand",
        "Teal boots",
        "Teal gloves",
        "Teal robe bottoms",
        "Teal robe top",
        "Team cape i",
        "Team cape x",
        "Team cape zero",
        "Thammarons sceptre",
        "Thieving bag",
        "Thieving cape",
        "Thieving hood",
        "Three barrels",
        "Toktz ket xil",
        "Toktz mej tal",
        "Toktz xil ak",
        "Toktz xil ek",
        "Toktz xil ul",
        "Tome of fire",
        "Tome of water",
        "Top hat & monocle",
        "Topaz amulet",
        "Topaz bolts",
        "Topaz bolts (e)",
        "Topaz bracelet",
        "Topaz dragon bolts",
        "Topaz necklace",
        "Topaz ring",
        "Torags hammers",
        "Torags helm",
        "Torags platebody",
        "Torags platelegs",
        "Tormented bracelet",
        "Torva full helm",
        "Torva platebody",
        "Torva platelegs",
        "Toxic blowpipe",
        "Trailblazer axe",
        "Trailblazer banner",
        "Trailblazer cane",
        "Trailblazer harpoon",
        "Trailblazer pickaxe",
        "Trailblazer trophy",
        "Training arrows",
        "Training bow",
        "Training shield",
        "Training sword",
        "Treasonous ring",
        "Treasonous ring (i)",
        "Treasure flag",
        "Tree skirt",
        "Tri jester hat",
        "Tri jester scarf",
        "Tribal mask (blue)",
        "Tribal mask (green)",
        "Tribal mask (orange)",
        "Tribal top (blue)",
        "Tribal top (brown)",
        "Tribal top (pink)",
        "Tribal top (yellow)",
        "Trident of the seas",
        "Trident of the swamp",
        "Trollweiss",
        "Trousers (blue)",
        "Trousers (brown)",
        "Trousers (lilac)",
        "Tumekens heka",
        "Turquoise boots",
        "Turquoise hat",
        "Turquoise robe top",
        "Twisted ancestral hat",
        "Twisted banner",
        "Twisted bow",
        "Twisted bronze trophy",
        "Twisted buckler",
        "Twisted cane",
        "Twisted dragon trophy",
        "Twisted iron trophy",
        "Twisted rune trophy",
        "Twisted slayer helmet",
        "Twisted steel trophy",
        "Two barrels",
        "Tyrannical ring",
        "Tyrannical ring (i)",
        "Tyras helm",
        "Tzhaar ket em",
        "Tzhaar ket om",
        "Tzhaar ket om (t)",
        "Tzkal slayer helmet",
        "Tztok slayer helmet",
        "Ugly halloween jumper",
        "Ultimate ironman helm",
        "Unblessed symbol",
        "Unholy blessing",
        "Unholy book",
        "Unholy book (or)",
        "Unholy symbol",
        "Unpowered symbol",
        "Uris hat",
        "Vs shield",
        "Vampyrium vambraces",
        "Veracs brassard",
        "Veracs flail",
        "Veracs helm",
        "Veracs plateskirt",
        "Vestas chainbody",
        "Vestas longsword",
        "Vestas plateskirt",
        "Vestas spear",
        "Viggoras chainmace",
        "Villager hat (blue)",
        "Villager hat (brown)",
        "Villager hat (pink)",
        "Villager hat (yellow)",
        "Villager robe (blue)",
        "Villager robe (brown)",
        "Villager robe (pink)",
        "Virtus mask",
        "Virtus robe bottoms",
        "Virtus robe top",
        "Void knight gloves",
        "Void knight mace",
        "Void knight robe",
        "Void knight robe (or)",
        "Void knight top",
        "Void knight top (or)",
        "Void mage helm",
        "Void mage helm (or)",
        "Void melee helm",
        "Void melee helm (or)",
        "Void ranger helm",
        "Void ranger helm (or)",
        "Void seal",
        "Volcanic abyssal whip",
        "Vyre noble legs",
        "Vyre noble shoes",
        "Vyre noble top",
        "Vyre noble vest (red)",
        "Vyrewatch legs",
        "Vyrewatch shoes",
        "Vyrewatch top",
        "War blessing",
        "Warm gloves",
        "Warrior helm",
        "Warrior ring",
        "Warrior ring (i)",
        "Water battlestaff",
        "Water tiara",
        "White 2h sword",
        "White apron",
        "White battleaxe",
        "White beret",
        "White boater",
        "White boots",
        "White cavalier",
        "White chainbody",
        "White claws",
        "White dagger",
        "White elegant blouse",
        "White elegant skirt",
        "White flowers",
        "White full helm",
        "White gloves",
        "White halberd",
        "White headband",
        "White kiteshield",
        "White longsword",
        "White mace",
        "White magic staff",
        "White med helm",
        "White partyhat",
        "White platebody",
        "White platelegs",
        "White plateskirt",
        "White scimitar",
        "White sq shield",
        "White sword",
        "White unicorn mask",
        "White warhammer",
        "Willow blackjack",
        "Willow blackjack(d)",
        "Willow blackjack(o)",
        "Willow comp bow",
        "Willow longbow",
        "Willow shield",
        "Willow shortbow",
        "Witchwood icon",
        "Wizard boots",
        "Wizard hat",
        "Wolf cloak",
        "Wolf mask",
        "Wood camo legs",
        "Wood camo top",
        "Woodcutting cape",
        "Woodcutting hood",
        "Wooden shield",
        "Wooden shield (g)",
        "Wooden spoon",
        "Wooden sword",
        "Woolly hat",
        "Woolly scarf",
        "Woven top (blue)",
        "Woven top (brown)",
        "Woven top (yellow)",
        "Wrath tiara",
        "Xerics champion",
        "Xerics general",
        "Xerics guard",
        "Xerics sentinel",
        "Xerics talisman",
        "Xerics warrior",
        "Xerician hat",
        "Xerician robe",
        "Xerician top",
        "Yak hide armour (top)",
        "Yellow boots",
        "Yellow cape",
        "Yellow flowers",
        "Yellow gloves",
        "Yellow hat",
        "Yellow partyhat",
        "Yellow robe bottoms",
        "Yellow robe top",
        "Yew comp bow",
        "Yew longbow",
        "Yew shield",
        "Yew shortbow",
        "Yin yang amulet",
        "Zamorak banner",
        "Zamorak bracers",
        "Zamorak cape",
        "Zamorak chaps",
        "Zamorak cloak",
        "Zamorak coif",
        "Zamorak crozier",
        "Zamorak dhide body",
        "Zamorak dhide boots",
        "Zamorak dhide shield",
        "Zamorak full helm",
        "Zamorak godsword",
        "Zamorak godsword (or)",
        "Zamorak halo",
        "Zamorak kiteshield",
        "Zamorak max cape",
        "Zamorak max hood",
        "Zamorak mitre",
        "Zamorak mjolnir",
        "Zamorak monk bottom",
        "Zamorak monk top",
        "Zamorak platebody",
        "Zamorak platelegs",
        "Zamorak plateskirt",
        "Zamorak robe legs",
        "Zamorak robe top",
        "Zamorak staff",
        "Zamorak stole",
        "Zamorakian hasta",
        "Zamorakian spear",
        "Zaryte bow",
        "Zaryte crossbow",
        "Zaryte vambraces",
        "Zealots boots",
        "Zealots helm",
        "Zealots robe bottom",
        "Zealots robe top",
        "Zenyte amulet",
        "Zenyte bracelet",
        "Zenyte necklace",
        "Zenyte ring",
        "Zombie boots",
        "Zombie gloves",
        "Zombie mask",
        "Zombie monkey",
        "Zombie shirt",
        "Zombie trousers",
        "Zuriels hood",
        "Zuriels robe bottom",
        "Zuriels robe top",
        "Zuriels staff"
    ];
export const ROWS_ON_BOARD = 10;
export const LETTER_NOT_PRESENT = 0;
export const LETTER_PRESENT_NOT_HERE = 1;
export const LETTER_CORRECT = 2;
export const CHAR_CODES = {
            ' ': 32,
            '(': 40,
            ')': 41,
            '0': 48,
            '1': 49,
            '2': 50,
            '3': 51,
            '4': 52,
            '5': 53,
            '6': 54,
            '7': 55,
            '8': 56,
            '9': 57,
            'A': 65,
            'B': 66,
            'C': 67,
            'D': 68,
            'E': 69,
            'F': 70,
            'G': 71,
            'H': 72,
            'I': 73,
            'J': 74,
            'K': 75,
            'L': 76,
            'M': 77,
            'N': 78,
            'O': 79,
            'P': 80,
            'Q': 81,
            'R': 82,
            'S': 83,
            'T': 84,
            'U': 85,
            'V': 86,
            'W': 87,
            'X': 88,
            'Y': 89,
            'Z': 90,
            'Enter': 13,
            'Backspace': 8
        };